fix/PLF-8765: Oauth integration: sign up/in with linkedin account iss…
Meeds-io/portal pull request #14
Opened 2020-04-16 22:35 UTC by lbengayed

…ue migrate to Oauth2

2020-04-22 12:00 UTC, ahamdi requested changes
- Please add a unit test
 - Please check that during the build, the right version of scribe library is used

2020-04-22 12:00 UTC, ahamdi commented on component/web/oauth-common/src/main/java/org/gatein/security/oauth/linkedin/LinkedinProcessorImpl.java
> +    private final String scope="r_liteprofile r_emailaddress w_member_social";
```suggestion
    private final String scope = "r_liteprofile r_emailaddress w_member_social";
```

2020-04-22 12:00 UTC, ahamdi commented on component/web/oauth-web/src/main/java/org/gatein/security/oauth/web/OAuthProviderFilter.java
>              log.warn("Error during OAuth flow with: " + ex.getMessage());
Change it to error and print the exception please

2020-04-22 12:00 UTC, ahamdi commented on pom.xml
>      <version.scribe>1.3.5</version.scribe>
to remove this one if replaced by newer version.

2020-04-23 17:10 UTC, lbengayed commented on pom.xml
>      <version.scribe>1.3.5</version.scribe>
it used to import Token and OAuthService to verify if the token null or no [https://github.com/Meeds-io/gatein-portal/pull/14/files#diff-4b6c1978f7bb2d0fad7bf290fe443d51R114](url)

2020-04-27 10:58 UTC, ahamdi requested changes

2020-04-27 10:58 UTC, ahamdi commented on component/web/oauth-common/src/main/java/org/gatein/security/oauth/linkedin/LinkedinProcessorImpl.java
> +        String encodedAccessTokenSecret = codec.encodeString(accessToken.accessToken.getAccessToken());
What is the difference between those variables ? aren't they the same ?

2020-04-27 10:58 UTC, ahamdi commented on component/web/oauth-common/src/test/java/org/gatein/security/oauth/test/TestOAuthPrincipalProcessor.java
> +
This tests the Scribe Java API, we need to test LinkedinProcessorImpl.java instead

2020-04-30 08:03 UTC, ahamdi approved these changes
LGTM

2020-04-30 09:53 UTC, merged