TASK-41619 : Synchronisation AD - User status
Meeds-io/portal pull request #183
Opened 2021-03-25 16:11 UTC by GouadriaHanen

added enabled to attributes while retrieving users from AD

2021-03-30 19:12 UTC, ahamdi requested changes

2021-03-30 19:12 UTC, ahamdi commented on component/identity/src/main/java/org/exoplatform/services/organization/idm/IDMUserListAccess.java
> +            if ((this.userStatus == UserStatus.ENABLED || this.userStatus == UserStatus.DISABLED)) {
Why did you remove the boolean isDbOnly ?

2021-03-30 19:12 UTC, ahamdi commented on component/identity/src/main/java/org/exoplatform/services/organization/idm/IDMUserListAccess.java
> +                if ((userStatus == UserStatus.ENABLED && attr == null) || (userStatus == UserStatus.DISABLED && attr != null && attr.getValue().toString().equals("false"))|| (userStatus == UserStatus
Could you combine this check with the first one in the same instruction ?

2021-03-30 19:12 UTC, ahamdi commented on component/identity/src/main/java/org/picketlink/idm/impl/store/hibernate/PatchedHibernateIdentityStoreImpl.java
> +               if ((entry.getValue() == null || entry.getValue().length == 0) && mappedAttributeName!= "enabled") {
Could you tell more about this check ?

2021-03-30 19:12 UTC, ahamdi commented on component/identity/src/main/java/org/picketlink/idm/impl/store/hibernate/PatchedHibernateIdentityStoreImpl.java
> -            // If the attribute key is enable, consider its absence as it was equals to true
Could youi tell more about this change ?

2021-03-31 10:16 UTC, GouadriaHanen commented on component/identity/src/main/java/org/exoplatform/services/organization/idm/IDMUserListAccess.java
> +            if ((this.userStatus == UserStatus.ENABLED || this.userStatus == UserStatus.DISABLED)) {
removed to always filter by status when retrieving by status

2021-03-31 10:16 UTC, GouadriaHanen commented on component/identity/src/main/java/org/picketlink/idm/impl/store/hibernate/PatchedHibernateIdentityStoreImpl.java
> +               if ((entry.getValue() == null || entry.getValue().length == 0) && mappedAttributeName!= "enabled") {
"enabled" is added to attributes so the query becomes " and not exists(from io.attributes as attrTableJoinName where attrTableJoinName.name = :enabled " will return an empty slice

2021-03-31 10:16 UTC, GouadriaHanen commented on component/identity/src/main/java/org/exoplatform/services/organization/idm/IDMUserListAccess.java
> +                if ((userStatus == UserStatus.ENABLED && attr == null) || (userStatus == UserStatus.DISABLED && attr != null && attr.getValue().toString().equals("false"))|| (userStatus == UserStatus
No, it is not the same

2021-03-31 10:16 UTC, GouadriaHanen commented on component/identity/src/main/java/org/picketlink/idm/impl/store/hibernate/PatchedHibernateIdentityStoreImpl.java
> -            // If the attribute key is enable, consider its absence as it was equals to true
an internal user may have its status null means that he is enabled

2021-04-19 11:30 UTC, ahamdi approved these changes

2021-04-19 11:30 UTC, merged