TASK-44539 : improved disabled user detection from AD
Meeds-io/portal pull request #224
Opened 2021-06-02 14:50 UTC by nidhalnidhal

Before this fix , disabled user from AD are detected only if the value of UserAccessControl attribute is equal to 514 , so i generalized the detection for all values and now the rule is:  an AD  user is disabled if UserAccessContral attribute is equal to ( (2 to the (power) n )+ 2) ) . this modification took place in EntityMapperUtils class.

2021-06-02 14:57 UTC, ahamdi requested changes
We need to add a Unit test to cover this class with different samples of status values.

2021-06-02 16:08 UTC, plamarque commented on component/identity/src/main/java/org/exoplatform/services/organization/idm/EntityMapperUtils.java
> +    String BinaryStatus = Integer.toBinaryString(status);
```suggestion
    String binaryStatus = Integer.toBinaryString(status);
```

2021-06-02 16:08 UTC, plamarque commented on component/identity/src/main/java/org/exoplatform/services/organization/idm/EntityMapperUtils.java
> +    if(BinaryStatus.charAt(BinaryStatus.length()-2) == '1') {
```suggestion
    if(binaryStatus.charAt(BinaryStatus.length()-2) == '1') {
```

2021-06-02 16:12 UTC, plamarque reviewed
Some explanation of why these codes all represent a disabled user would be helpful too
(leave in code + add unit test should let a reader understand the unobvious)

2021-06-03 10:52 UTC, hbenali requested changes
Please format your code

2021-06-03 10:52 UTC, hbenali commented on component/identity/src/test/java/org/exoplatform/services/organization/TestLDAPOrganization.java
> +  public void testEnabledUserDetection() throws Exception{
```suggestion

  public void testEnabledUserDetection() throws Exception{
```
Please format your code. Please check http://developer.exoplatform.org/#id-intellij-settings

2021-06-03 10:52 UTC, hbenali commented on component/identity/src/main/java/org/exoplatform/services/organization/idm/EntityMapperUtils.java
> +  private static Boolean isUserEnabled (int status) {
Also here please

2021-06-03 13:04 UTC, ahamdi approved these changes

2021-06-03 13:08 UTC, hbenali approved these changes

2021-06-03 13:38 UTC, merged