Productization_US01: [7] Productize Branding
Meeds-io/portal pull request #31
Opened 2020-06-17 16:27 UTC by Rdidmohamedelhadi

2020-06-17 19:02 UTC, azayati requested changes
See review

2020-06-17 19:02 UTC, azayati commented on portlet/exoadmin/src/main/webapp/company-branding-app/components/ExoCompanyBranding.vue
> +          <input id="companyNameInput" v-model="branding.companyName" :placeholder="$t('companyName.placeholder')" type="text" name="formOp" style="margin-top: 4px;margin-left: -9px;width: 32%;" clas
don't add style directly

2020-06-17 19:02 UTC, azayati commented on portlet/exoadmin/src/main/webapp/company-branding-app/components/ExoCompanyBranding.vue
> +                <i v-if="!removeLogoButtonDisplayed" :title="$t('branding.message.change.logo')" class="uiIconEdit iconEdit" rel="tooltip" data-placement="bottom" @click="editLogo"></i>
v-else instead

2020-06-17 19:02 UTC, azayati commented on portlet/exoadmin/src/main/webapp/company-branding-app/components/ExoCompanyBranding.vue
> +                <img id="previewLogoImg" :src="logoPreview" alt="" class="previewImg">
empty alt not needed ?

2020-06-17 19:02 UTC, azayati commented on portlet/exoadmin/src/main/webapp/company-branding-app/components/ExoCompanyBranding.vue
> +                  <div class="firstBlock">
privilege significant name for the classes

2020-06-17 19:02 UTC, azayati commented on portlet/exoadmin/src/main/webapp/company-branding-app/components/ExoCompanyBranding.vue
> +          <v-row class="blockColors">
```suggestion
          <v-row class="colorsBlock">
```

2020-06-17 19:02 UTC, azayati commented on portlet/exoadmin/src/main/webapp/company-branding-app/components/ExoCompanyBranding.vue
> +    console.log(brandingConstants.HOMEICON);
remove console.log

2020-06-17 19:02 UTC, azayati commented on portlet/exoadmin/src/main/webapp/company-branding-app/components/ExoCompanyBranding.vue
> +    editLogo(){
you can put this directly in the template

2020-06-17 19:02 UTC, azayati commented on portlet/exoadmin/src/main/webapp/company-branding-app/components/modal/ExoColorPicker.vue
> +        <div :style="{ backgroundColor: value}" style="width:47px;height:47px;margin-top:5px;margin-right:10px;cursor: pointer" v-on="on">
Avoid using style directly

2020-06-17 19:02 UTC, azayati commented on portlet/exoadmin/src/main/webapp/company-branding-app/components/modal/ExoColorPicker.vue
> +          <label style="cursor: pointer" v-on="on">{{ value }}</label>
Avoid using style directly

2020-06-17 19:02 UTC, azayati commented on portlet/exoadmin/src/main/resources/locale/portlet/exoadmin/Branding_en.properties
> +branding.message.remove.logo=Click here to restore the default logo
```suggestion
branding.message.restore.logo=Click here to restore the default logo
```

2020-06-18 15:10 UTC, Rdidmohamedelhadi commented
> See review

I know it's just for fast testing :)

2020-06-23 22:17 UTC, azayati approved these changes
LGTM

2020-06-23 23:27 UTC, merged