Task-52381: Token are not deleted after consumption.
Meeds-io/portal pull request #312
Opened 2022-01-11 11:07 UTC by Montassar-Hamadi

Problem: When user forgot his password, he when to reset it by sending a link to his mail which gives him the hand to change his password. So the problem has happened when he send many links to mail to reset the password, all links kept available to change his password Even if he did it the first time. all this happened because every time a link is sent to his mail a token is generated and stored automatically in the database, so the recent tokens keep stored even if he consumes one of them that's why we could reset the password by every link sent.

Fix: The solution is to remove all tokens associate with this user after he succeeds to reset his password. I use the function deleteTokensOfUser(username) of service RemindPasswordTokenService .this function is executed after every password is changed to delete all Tokens of the user stored in DB then the recent links will be not available.

2022-01-11 13:05 UTC, rdenarie requested changes
Your solution deletes all user's tokens, without checking the type 
Token type can be 

   ```
public static final String ONBOARD_TOKEN="onboard";
public static final String FORGOT_PASSWORD_TOKEN="forgot-password";
public static final String EXTERNAL_REGISTRATION_TOKEN="external-registration";
```
we need to delete only forgot-password token here

In addition, the task ask for 

> We must also check the same scenario with invite external user, and onboarding. In both case, if the user have more than one email with token, a successful action must invalidate residual tokens

So we need a similar mechanism for onboard an invite external features

2022-01-13 13:00 UTC, rdenarie requested changes

2022-01-13 13:00 UTC, rdenarie commented on component/web/security/src/main/resources/db/changelog/gatein-token.db.changelog-1.0.0.xml
> +  </changeSet>
This created a problem when you start with an existing database : 
- Get fresh 6.3.x-maintenance
- Start, create user root and make a forgot-password to request a token
- Ensure that the token is created in database
- Stop server
- deploy your fix
- start the server

There is an error in logs : 
`2022-01-13 13:57:00,308 | ERROR | db/changelog/gatein-token.db.changelog-1.0.0.xml: db/changelog/gatein-token.db.changelog-1.0.0.xml::1.0.0-3::gatein-token: Change Set db/changelog/gatein-token.db.changelog-1.0.0.xml::1.0.0-3::gatein-token failed.  Error: default expression needed in statement [ALTER TABLE PUBLIC.PORTAL_TOKENS ADD TOKEN_TYPE VARCHAR(250) NOT NULL] [Failed SQL: ALTER TABLE PUBLIC.PORTAL_TOKENS ADD TOKEN_TYPE VARCHAR(250) NOT NULL] [liquibase<localhost-startStop-7>] 
liquibase.exception.DatabaseException: default expression needed in statement [ALTER TABLE PUBLIC.PORTAL_TOKENS ADD TOKEN_TYPE VARCHAR(250) NOT NULL] [Failed SQL: ALTER TABLE PUBLIC.PORTAL_TOKENS ADD TOKEN_TYPE VARCHAR(250) NOT NULL]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1251)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1234)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:554)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
	at liquibase.Liquibase.update(Liquibase.java:212)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.Liquibase.update(Liquibase.java:188)
	at liquibase.Liquibase.update(Liquibase.java:181)
	at org.exoplatform.commons.persistence.impl.LiquibaseDataInitializer.applyChangeLog(LiquibaseDataInitializer.java:169)
	at org.exoplatform.commons.persistence.impl.LiquibaseDataInitializer.initData(LiquibaseDataInitializer.java:150)
	at org.exoplatform.commons.persistence.impl.LiquibaseDataInitializer.initData(LiquibaseDataInitializer.java:112)
	at org.exoplatform.commons.persistence.impl.LiquibaseDataInitializer.start(LiquibaseDataInitializer.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.exoplatform.container.LifecycleVisitor.traverse(LifecycleVisitor.java:103)
	at org.exoplatform.container.LifecycleVisitor.start(LifecycleVisitor.java:166)
	at org.exoplatform.container.ConcurrentContainer.start(ConcurrentContainer.java:472)
	at org.exoplatform.container.AbstractContainer.start(AbstractContainer.java:67)
	at org.exoplatform.container.AbstractContainer.start(AbstractContainer.java:67)
	at org.exoplatform.container.AbstractContainer.start(AbstractContainer.java:67)
	at org.exoplatform.container.ExoContainer.start(ExoContainer.java:309)
	at org.exoplatform.container.ExoContainer.start(ExoContainer.java:282)
	at org.exoplatform.container.RootContainer$7.run(RootContainer.java:881)
	at org.exoplatform.container.RootContainer$7.run(RootContainer.java:875)
	at org.exoplatform.commons.utils.SecurityHelper.doPrivilegedExceptionAction(SecurityHelper.java:311)
	at org.exoplatform.container.RootContainer.buildRootContainer(RootContainer.java:874)
	at org.exoplatform.container.RootContainer.getInstance(RootContainer.java:957)
	at org.exoplatform.web.GenericHttpListener.contextInitialized(GenericHttpListener.java:156)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5168)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1015)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1895)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLSyntaxErrorException: default expression needed in statement [ALTER TABLE PUBLIC.PORTAL_TOKENS ADD TOKEN_TYPE VARCHAR(250) NOT NULL]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy13.execute(Unknown Source)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
	... 46 common frames omitted
Caused by: org.hsqldb.HsqlException: default expression needed
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.TableWorks.addColumn(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 55 common frames omitted
`

2022-01-14 14:27 UTC, rdenarie requested changes
Ok for 

- Forgot password tokens
- Onboarding token

If I create 2 forgot password otken, use the first link in mail, then successul change passwork, then click on the second link, the second link is mark as expired
Same for onboarding

But it seems KO for external user invitation :

- Create a space space1
- invite external user into : jsmith@acme.com
- create space space2
- invite external user into : jsmith@acme.com
- click on mail inviting in space1 : create account. Check database, both token are still there. Expected : both token removed

2022-01-17 13:18 UTC, rdenarie requested changes
Please fix the sonar issue

2022-01-17 13:18 UTC, rdenarie commented on component/web/security/src/main/java/org/exoplatform/web/login/externalRegistration/ExternalRegistrationHandler.java
> +                    remindPasswordTokenService.deleteTokensByUsernameAndType(email,remindPasswordTokenService.EXTERNAL_REGISTRATION_TOKEN);
If there is an error in the user creation, I'm afraid that token are dropped.
Can you delete token only if we send externalConfirmationAccount email

2022-01-18 12:32 UTC, rdenarie requested changes
Please fix the sonar code smell

2022-01-19 09:20 UTC, boubaker commented on component/web/security/src/main/resources/db/changelog/gatein-token.db.changelog-1.0.0.xml
> +  <changeSet author="gatein-token" id="1.0.0-3">
```suggestion
  <changeSet author="gatein-token" id="1.0.0-4">
```

2022-01-19 13:31 UTC, rdenarie reviewed
Please fix the sonar feedback

2022-01-19 14:27 UTC, rdenarie approved these changes

2022-01-19 14:44 UTC, merged