MAINT-45289: Avoid having a null portalowner value in PortalRequestContext
Meeds-io/portal pull request #321
Opened 2022-01-28 13:39 UTC by hakermi

**ISSUE**: Sometimes the notification of activities redirects to 404 error page, because of a null value of `portalOwner` in the URL.
**FIX**: THis fix should maintain the `getPortalOwner` function to avoid having such null value in the `portalOwner` by add a check and sending the default `portalOnwer` if the value is null

2022-01-28 16:20 UTC, rdenarie requested changes
This modification could have a huge impact as it is used in a lot of class of the platform.
Is it possible to isolate which part call this to generate the news notification, and make a specific treatement if getPortalOwner return null ?

I'm afraid of side effects with this current solution

2022-01-28 16:44 UTC, hakermi commented
> This modification could have a huge impact as it is used in a lot of class of the platform. Is it possible to isolate which part call this to generate the news notification, and make a specific treatement if getPortalOwner return null ?
> 
> I'm afraid of side effects with this current solution

I want to fix the source of the issue, it's juts a null check and return of default portalOwner

2022-01-31 08:08 UTC, hakermi commented
> This modification could have a huge impact as it is used in a lot of class of the platform. Is it possible to isolate which part call this to generate the news notification, and make a specific treatement if getPortalOwner return null ?
> 
> I'm afraid of side effects with this current solution

@rdenarie  Could you check now ? i replaced it with the function in `commonUtils` which treats the null value

2022-02-05 14:14 UTC, rdenarie approved these changes

2022-02-05 14:15 UTC, merged