Task-58297: Refactor OIDC protocol
Meeds-io/portal pull request #391
Opened 2022-06-29 16:43 UTC by hchaabene

2022-07-01 14:55 UTC, rdenarie requested changes

2022-07-01 14:55 UTC, rdenarie commented on component/web/oauth-common/pom.xml
> +      <version>1.0.4</version>
you should not haev a version here

2022-07-01 14:55 UTC, rdenarie commented on component/web/oauth-common/src/main/java/org/gatein/security/oauth/service/OIDCService.java
> +package org.gatein.security.oauth.service;
Not needed class

2022-07-01 14:55 UTC, rdenarie commented on component/web/oauth-common/src/main/java/org/gatein/security/oauth/service/MfaSystemService.java
> +package org.gatein.security.oauth.service;
Not needed class

2022-07-01 14:55 UTC, rdenarie commented on component/web/oauth-common/src/main/java/org/gatein/security/oauth/openid/OpenIdProcessorImpl.java
> +        this.oidcService = oidcService;
```suggestion

```

2022-07-01 14:55 UTC, rdenarie commented on component/web/oauth-common/src/main/java/org/gatein/security/oauth/openid/OpenIdProcessorImpl.java
> +import org.gatein.security.oauth.service.OIDCService;
```suggestion
```

2022-07-01 14:55 UTC, rdenarie commented on component/web/oauth-common/src/main/java/org/gatein/security/oauth/openid/OpenIdProcessorImpl.java
> +    private  final  OIDCService oidcService;
```suggestion
```

2022-07-01 14:55 UTC, rdenarie commented on component/web/oauth-common/src/main/java/org/gatein/security/oauth/openid/OpenIdProcessorImpl.java
> +    public OpenIdProcessorImpl(ExoContainerContext context, InitParams params, SecureRandomService secureRandomService, OIDCService oidcService) {
```suggestion
    public OpenIdProcessorImpl(ExoContainerContext context, InitParams params, SecureRandomService secureRandomService) {
```

2022-07-01 14:55 UTC, rdenarie commented on component/web/oauth-common/pom.xml
> +      <version>1.1</version>
no version here

2022-07-04 14:02 UTC, rdenarie requested changes

2022-07-04 14:02 UTC, rdenarie commented on component/web/oauth-common/src/main/java/org/gatein/security/oauth/openid/RemoteJwkSigningKeyResolver.java
> +package org.gatein.security.oauth.openid;
Can you add the correct header for meeds ?

2022-07-04 14:38 UTC, rdenarie approved these changes

2022-07-04 14:52 UTC, hchaabene commented
Refactor OIDC protocol
i moved class RemoteSigningKeyResolver from mfa-oidc to gatein-portal

2022-07-04 14:52 UTC, merged