feat: create the new container category Table -EXO-61139 -Meeds-io/MIPs#37
Meeds-io/portal pull request #476
Opened 2022-12-09 15:31 UTC by sofyenne

2022-12-09 16:07 UTC, azayati requested changes

2022-12-09 16:07 UTC, azayati commented on web/eXoResources/src/main/webapp/skin/DefaultSkin/portal/webui/component/customization/UIContainerList/Stylesheet.css
> +/**
keep the same indentation

2022-12-12 12:41 UTC, sofyenne commented on web/eXoResources/src/main/webapp/skin/DefaultSkin/portal/webui/component/customization/UIContainerList/Stylesheet.css
> +/**
done !

2022-12-12 12:41 UTC, sofyenne commented on web/eXoResources/src/main/webapp/skin/DefaultSkin/portal/webui/component/customization/UIContainerList/Stylesheet.css
> +/**
done !

2022-12-12 14:22 UTC, azayati requested changes

2022-12-12 14:22 UTC, azayati commented on web/eXoResources/src/main/webapp/skin/DefaultSkin/portal/webui/component/customization/UIContainerList/Stylesheet.css
> +.UIContainerList .SimpleTableContainerLayout	{
```suggestion
.UIContainerList .SimpleTableContainerLayout {
```

2022-12-12 14:22 UTC, azayati commented on web/eXoResources/src/main/webapp/skin/DefaultSkin/portal/webui/component/customization/UIContainerList/Stylesheet.css
> +	background: transparent url(background/OneRowContainerLayout-rt.gif) no-repeat right 10px; /* orientation=rt */
```suggestion
	background: transparent url(background/SimpleTableContainerLayou-rt.gif) no-repeat right 10px; /* orientation=rt */
```

2022-12-12 14:22 UTC, azayati commented on web/portal/src/main/webapp/groovy/portal/webui/container/UISimpleTableContainer.gtmpl
> +<div class="UIContainer Simple-Table-Container<%=uiComponentClass%> EdittingContainer<%=uicomponent.getPermissionClasses()%>"
```suggestion
<div class="UIContainer simpleTableContainer <%=uiComponentClass%> EdittingContainer<%=uicomponent.getPermissionClasses()%>"
```

2022-12-12 14:22 UTC, azayati commented on web/portal/src/main/webapp/groovy/portal/webui/container/UISimpleTableContainer.gtmpl
> +<div class="UIContainer Simple-Table-Container<%=uiComponentClass%> <%=hasAccessPermission?"": "ProtectedContainer"%>" id="${uicomponent.id}" ${normalCssStyle}>
```suggestion
<div class="UIContainer simpleTableContainer <%=uiComponentClass%> <%=hasAccessPermission?"": "ProtectedContainer"%>" id="${uicomponent.id}" ${normalCssStyle}>
```

2022-12-12 14:22 UTC, azayati commented on web/portal/src/main/webapp/groovy/portal/webui/container/UISimpleTableContainer.gtmpl
> +        normalCssStyle += "\"";
```suggestion
	String cssStyle = "";
	String uiComponentWidth = uicomponent.getWidth();
	String uiComponentHeight = uicomponent.getHeight();
	if(uiComponentWidth != null || uiComponentHeight != null) cssStyle = "style=\"";
	if(uiComponentWidth != null) cssStyle += "width: "+uiComponentWidth+";"
	if(uiComponentHeight != null) cssStyle += "height: "+uiComponentHeight+";"
	if(cssStyle.length() > 0) cssStyle += "\"";
```

2022-12-13 10:26 UTC, azayati approved these changes
LGTM

2022-12-13 10:27 UTC, merged