fix: TOP bar menu isn't displayed - EXO-62924
Meeds-io/portal pull request #548
Opened 2023-03-02 13:31 UTC by GouadriaHanen

prior to this change, the top bar menu is not displayed and an error 500 is thrown since  it can not create a new sitekey with siteTypeName in uppercase
after this change, the siteTypeName is lowercased and the top bar menu is displayed

2023-03-02 13:48 UTC, rdenarie reviewed
Did we understand WHY the sitetypename is upper case on maintenance acceptance ? 
Why other instances are not impacted ?

Without answer to theses questions, we are not sure that this fix is the better thing to do.
cc @ahamdi

2023-03-02 13:53 UTC, rdenarie commented
In fact, the siteType is 'PORTAL' since few month, on Tribe, we can see 'PORTAL' also.
Why now, it is no more working with 'PORTAL' ?

2023-03-02 14:44 UTC, rdenarie commented
In fact, we have here a problem. 

Firstly the service v1/navigations is not correctly used in TopBarNavigationMenu. 
It is used by calling this url 
/portal/rest/v1/navigations/portal?siteType=PORTAL&siteName=dw....
but it should be called like this : 
/portal/rest/v1/navigations/PORTAL?siteName=dw....

This problem was fixed by Boubaker on develop here : 
https://github.com/Meeds-io/social/commit/30ce7e53b690a1ff17d3098b741ccb7f5b7d2df5#diff-5ca4ff1d7eff1f0e5dba8bb6ca0e57e756ba065318bffb35ece53df1c854857eR36

This problem leads to another problem : when creating a SiteKey, the siteType should be compared case incensitively. This modification was also done by Boubaker here : 
https://github.com/Meeds-io/gatein-portal/commit/2cc07cb10afa0287d1cd70b0709a4daab7ee7a0d#diff-f142ca2eb2e3d1e8a781ac7f489d82f3f076b5607c65341d65e66d60e7d20cc4R70
But this commit is still only on develop-meed and will arrive on develop in few days, we are reviewing the PR.
Once this PR will be merged, we will have the fix of this task on develop, without your fix.

So we can : 
- do nothing on develop, then the Boubaker PR will fix the problem. do nothing on stable/6.4.x as it is working, even if we are lucky that it is working
- Do nothing on develop, then the Boubaker PR will fix the problem. Then fix on 6.4.x NavigationService.js AND SiteKey.java. 
- Add the SiteKey fix on develop, but when the Boubaker's PR will arrive, we will have a conflict. AND fix on 6.4.x NavigationService.js AND SiteKey.java.

cc @ahamdi to discuss

2023-03-02 14:47 UTC, ahamdi approved these changes, later dismissed

2023-03-02 14:50 UTC, rdenarie requested changes
This fix is not sufficient

2023-03-03 11:10 UTC, rdenarie commented
Do we put this fix on develop ? 
I think we should not as it will arrive via meeds mip merge.

cc @ahamdi

2023-03-03 15:07 UTC, ahamdi approved these changes

2023-03-03 15:29 UTC, rdenarie commented
@ahamdi I think we should not add this commit on develop, because it is coming in a short time with a meeds fix.

We should only make this on develop

2023-03-03 15:37 UTC, GouadriaHanen commented
> @ahamdi I think we should not add this commit on develop, because it is coming in a short time with a meeds fix.
> 
> We should only make this on develop

this fix will be only included in maintenance Ft and backported to 6.4.x

2023-03-03 15:41 UTC, rdenarie commented
ok, did you also create a PR to fix in social the TopBarMenu portlet ?

2023-03-03 15:50 UTC, GouadriaHanen commented
> ok, did you also create a PR to fix in social the TopBarMenu portlet ?

since the changes are available in the development and maint FTs, the PR will be created only for the backport after validating the changes on maint.

2023-03-03 16:24 UTC, rdenarie commented
ok, youre right, sorry

2023-03-03 16:24 UTC, rdenarie approved these changes

2023-03-03 17:02 UTC, merged