feat: add new rest point for displayed sites with their root nodes - EXO-65477 - Meeds-io/MIPs#72
Meeds-io/portal pull request #652
Opened 2023-08-29 09:02 UTC by GouadriaHanen

2023-08-29 15:48 UTC, azayati requested changes

2023-08-29 15:48 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/NavigationRest.java
> +
we need a dedicated rest service for sites

2023-08-29 15:48 UTC, azayati commented on component/api/src/main/java/org/exoplatform/portal/mop/storage/SiteStorage.java
> +  List<PortalData> getPortalSitesOrderedByDisplayOrder();
this should be generic

2023-08-29 15:48 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/jdbc/entity/SiteEntity.java
> +@NamedQuery(
this should be generic

2023-08-29 15:48 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/dao/SiteDAO.java
> +  List<SiteEntity> findAPortalSitesOrderedByDisplayOrder();
this should be generic

2023-08-30 08:34 UTC, azayati requested changes

2023-08-30 08:34 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/jdbc/entity/SiteEntity.java
> +
remove that change

2023-08-30 08:34 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/NavigationRest.java
> +import org.exoplatform.portal.mop.rest.model.UserNodeRestEntity;
Remove that change

2023-08-30 08:34 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/SiteRestService.java
> +    @GET
indentation

2023-08-30 08:34 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/SiteRestService.java
> +    public Response getSitesWithNavigationNodes(@Context HttpServletRequest request,
```suggestion
    public Response getSites(@Context HttpServletRequest request,
```

2023-08-30 08:34 UTC, azayati commented on component/portal/src/test/java/org/exoplatform/portal/mop/rest/NavigationRestTest.java
> +import org.exoplatform.portal.mop.rest.model.UserNodeRestEntity;
Remove that change

2023-08-30 12:45 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-08-30 17:58 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-08-30 18:20 UTC, azayati approved these changes
LGTM

2023-08-30 18:50 UTC, merged