feat: Implement multilingual for site properties - EXO-65344 - Meeds-io/MIPs#72
Meeds-io/portal pull request #655
Opened 2023-08-31 08:54 UTC by IlhemEssaadi

2023-08-31 09:59 UTC, azayati requested changes
Change the title of the PR to describe only what it does

2023-08-31 09:59 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/storage/SiteStorageImpl.java
> +    }
you can use only on return here

2023-08-31 18:29 UTC, azayati requested changes

2023-08-31 18:29 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/storage/SiteStorageImpl.java
> +  @Override
is it possible to add a test into TestDataStorage.java ?

2023-08-31 18:29 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/service/LayoutServiceImpl.java
> +  public PortalConfig getPortalConfig(long siteId) {
can you add an UT for that ?

2023-09-01 15:51 UTC, azayati approved these changes
LGTM

2023-09-07 11:27 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-09-08 12:49 UTC, azayati approved these changes
LGTM

2023-09-08 12:49 UTC, merged