feat : implment breadcrumb portlet - EXO-66554 - Meeds-io/MIPs#87
Meeds-io/portal pull request #708
Opened 2023-10-31 16:31 UTC by GouadriaHanen

2023-11-07 08:33 UTC, azayati requested changes

2023-11-07 08:33 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/EntityBuilder.java
> +import java.util.*;
revert these imports

2023-11-07 08:33 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/model/UserNodeRestEntity.java
> +  }
```suggestion
  }
  
```

2023-11-07 08:33 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/EntityBuilder.java
> +
```suggestion
```

2023-11-07 08:33 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/EntityBuilder.java
> +  public static List<UserNodeBreadcrumbItem> getUserNodeBreadcrumbList(UserPortal userPortal, UserNode node) {
```suggestion
  private static List<UserNodeBreadcrumbItem> getUserNodeBreadcrumbList(UserPortal userPortal, UserNode node) {
```

2023-11-07 08:33 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/EntityBuilder.java
> +              expandBreadcrumb));
```suggestion
              false));
```
we don't need to expand breadcrumb for children

2023-11-07 08:33 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/EntityBuilder.java
> +  private static UserNode findTargetNode(String nodeName, Collection<UserNode> userNodes) {
not needed IMO since we need to the breadcrumb of the current node

2023-11-07 08:33 UTC, azayati commented on component/portal/src/main/java/org/exoplatform/portal/mop/rest/EntityBuilder.java
> +                                                                       node.getPageRef() != null ? node.getURI() : null);
we need also the target and the page link

2023-11-08 13:04 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-11-08 15:03 UTC, azayati approved these changes
LGTM

2023-11-08 15:03 UTC, merged