fix: fix sending email with user local when using user email - EXO-69927 - Meeds-io/meeds#1705
Meeds-io/portal pull request #845
Opened 2024-02-28 14:02 UTC by GouadriaHanen

before this change, when using the user email as userId in an email notification, the email is sent in EN even user's language setting is FR since it could not find a user by name with an email
After this change, when userId contains an @ we search for the user with its email

2024-02-28 14:03 UTC, mkrout approved these changes, later dismissed

2024-02-28 14:07 UTC, rdenarie requested changes
Hello,
In which cases getUserLocale is called with a userId containing an arobase ?

2024-02-28 14:12 UTC, rdenarie commented
I check the task, 
As I understand, this is called in agenda, when I invite someone by his email. 

As the search by email is time consuming, and not very performant, I think we should transform the email in a user name in agenda module, BEFORE creating the notification. 

getUserLocale called with a mail instead a username must occurs in only one case : the email is an external, and have no account in the platform

2024-02-29 12:49 UTC, GouadriaHanen commented
as proposed by @rdenarie this PR will be closed

2024-02-29 12:49 UTC, closed without merging