Task_35993: Make the changePassword feature extensible
Meeds-io/portal pull request #96
Opened 2020-11-02 18:31 UTC by azayati

2020-11-02 21:33 UTC, plamarque requested changes, later dismissed
typos.
Also don't forget to rename the email template file

2020-11-02 21:33 UTC, plamarque commented on component/web/security/src/main/java/org/exoplatform/web/login/recovery/PasswordRecoveryService.java
> +    public boolean sendOnbordingEmail(User user, Locale defaultLocale, StringBuilder url);
```suggestion
    public boolean sendOnboardingEmail(User user, Locale defaultLocale, StringBuilder url);
```

2020-11-02 21:33 UTC, plamarque commented on component/web/security/src/main/java/org/exoplatform/web/login/recovery/PasswordRecoveryServiceImpl.java
> +    public boolean sendOnbordingEmail(User user, Locale defaultLocale, StringBuilder url) {
```suggestion
    public boolean sendOnboardingEmail(User user, Locale defaultLocale, StringBuilder url) {
```

2020-11-02 21:33 UTC, plamarque commented on component/web/security/src/main/java/org/exoplatform/web/login/recovery/PasswordRecoveryServiceImpl.java
> +        String emailSubject = bundle.getString("onbording.email.header") + " " + brandingService.getCompanyName();
```suggestion
        String emailSubject = bundle.getString("onboarding.email.header") + " " + brandingService.getCompanyName();
```

2020-11-02 21:33 UTC, plamarque commented on component/web/security/src/main/java/org/exoplatform/web/login/recovery/PasswordRecoveryServiceImpl.java
> +    private String buildOnbordingEmailBody(User user, ResourceBundle bundle, String link) {
```suggestion
    private String buildOnboardingEmailBody(User user, ResourceBundle bundle, String link) {
```

2020-11-02 21:33 UTC, plamarque commented on component/web/security/src/main/java/org/exoplatform/web/login/recovery/PasswordRecoveryServiceImpl.java
> +      InputStream input = this.getClass().getClassLoader().getResourceAsStream("conf/onBording_email_template.html");
```suggestion
      InputStream input = this.getClass().getClassLoader().getResourceAsStream("conf/onBoarding_email_template.html");
```

2020-11-02 21:33 UTC, plamarque commented on component/web/security/src/main/resources/conf/onBording_email_template.html
> +                                                <p style="margin: 0 0 10px 0;line-height:22px">&{onbording.email.accessLink}: <a href="${RESET_PASSWORD_LINK}" style="text-decoration: none;color:#2e5d
```suggestion
                                                <p style="margin: 0 0 10px 0;line-height:22px">&{onboarding.email.accessLink}: <a href="${RESET_PASSWORD_LINK}" style="text-decoration: none;color:#2e5d97">&{onboarding.email.join}</a></p>
```

2020-11-02 21:33 UTC, plamarque commented on component/web/security/src/main/resources/conf/onBording_email_template.html
> +                                    <p style="margin: 10px 0 10px 0;line-height:22px">&{onbording.email.bye}.</p>
```suggestion
                                    <p style="margin: 10px 0 10px 0;line-height:22px">&{onboarding.email.bye}.</p>
```

2020-11-02 21:33 UTC, plamarque commented on component/web/security/src/main/resources/conf/onBording_email_template.html
> +                        <h2 style="color: #fff;margin: 0;padding: 0; font-size: 13px;">&{onbording.email.email.footer}</h2>
```suggestion
                        <h2 style="color: #fff;margin: 0;padding: 0; font-size: 13px;">&{onboarding.email.email.footer}</h2>
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_en.properties
> +onbording.email.subject=Invitation to join the platform
```suggestion
onboarding.email.subject=Invitation to join the platform
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_en.properties
> +onbording.email.header=Invitation to join the platform
```suggestion
onboarding.email.header=Invitation to join the platform
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_en.properties
> +onbording.email.hello=Hello
```suggestion
onboarding.email.hello=Hello
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_en.properties
> +onbording.email.welcome=You are invited to join the platform
```suggestion
onboarding.email.welcome=You are invited to join the platform
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_en.properties
> +onbording.email.accessLink=To access it click on the following link
```suggestion
onboarding.email.accessLink=To access it click on the following link
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_en.properties
> +onbording.email.join=Join
```suggestion
onboarding.email.join=Join
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_en.properties
> +onbording.email.bye=Thank you and very nice collaboration within your community!
```suggestion
onboarding.email.bye=Thank you and very nice collaboration within your community!
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_en.properties
> +onbording.email.email.footer=eXo Platform
```suggestion
onboarding.email.email.footer=eXo Platform
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_fr.properties
> +###### Onbording feature
```suggestion
###### Onboarding feature
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_fr.properties
> +onbording.email.subject=Invitation à rejoindre la platforme
```suggestion
onboarding.email.subject=Invitation à rejoindre la plateforme
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_fr.properties
> +onbording.email.header=Invitation à rejoindre la platforme
```suggestion
onboarding.email.header=Invitation à rejoindre la plateforme
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_fr.properties
> +onbording.email.hello=Bonjour
```suggestion
onboarding.email.hello=Bonjour
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_fr.properties
> +onbording.email.welcome=Vous êtes invité à rejoindre la plateforme
```suggestion
onboarding.email.welcome=Vous êtes invité(e) à rejoindre la plateforme
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_fr.properties
> +onbording.email.accessLink=Pour y accéder, veillez cliquer sur le lien suivant
```suggestion
onboarding.email.accessLink=Pour y accéder, veuillez cliquer sur le lien suivant
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_fr.properties
> +onbording.email.join=Rejoindre
```suggestion
onboarding.email.join=Rejoindre
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_fr.properties
> +onbording.email.bye=Merci et très belle collaboration au sein de votre communauté!
```suggestion
onboarding.email.bye=Merci et très belle collaboration au sein de votre communauté!
```

2020-11-02 21:33 UTC, plamarque commented on web/portal/src/main/resources/locale/portal/webui_fr.properties
> +onbording.email.email.footer=eXo Platform
```suggestion
onboarding.email.email.footer=eXo Platform
```

2020-11-02 22:31 UTC, azayati commented
@plamarque All done !

2020-11-03 08:23 UTC, rdenarie submitted a review, later dismissed
LGTM

2020-11-03 17:38 UTC, rdenarie submitted a review, later dismissed

2020-11-03 17:52 UTC, rdenarie approved these changes

2020-11-03 18:22 UTC, merged